### ISSUE TITLE
Postman environment file

### ISSUE THREAD

**Issue by sathishbalasubramaniyan-okta** [apigee/consumer-data-standards-au#8]
The test/postman folder does not include the Postman environment file. Could you please include it?

I would like to integrate this reference implementation with Okta as the IDP instead of the open source OIDC provider. Apigee needs to integrate with Okta via plain OIDC. Okta would return an authorization code that Apigee would need to exchange for an ID token and access token at Okta's token end-point (plain OIDC tokens). Apigee can get the user details from the Okta issued tokens. Then Apigee would need to handle consent and post consent, issue its own authorization code to the app, which the app would exchange for Apigee issued ID and access tokens at Apigee's token end-point that are CDR compliant. 

Appreciate if you could point me to the API proxies that need to be changed, the changes that need to be done at a high level etc.

**Comment by deboraelkin2** [comment]
The environment file is not included because it typically contains private information. You'll need to create your own environment. 

Regarding integrating Okta as the IDP, you'll need to modify the _oidc_ API proxy. It currently uses _oidc_mock_provider_ as the IDP (consent is handled by the IDP in this case) and implements the behaviour described in the sequence diagram found in https://github.com/apigee/consumer-data-standards-au/tree/master/src/apiproxies/oidc

It already issues authorization code, acceess and refresh tokens, but you'll need to adapt it to interact with Okta instead of the mock provider.

Once you've done that, you'll probably want to modify the _dynamic-client-registration_ API proxy. When a new client is registered the current implementaion also registers the client in the mock provider and reuses the same keys when registering the client in Apigee. Depending on the behaviour you want to implement you may want to either modify this proxy to register the client in Okta (with or without synchronising keys in between Okta and Apigee) or simply removing this step altogether, if you decide that Apigee is the only registered client in Okta and all other clients and managed solely by Apigee.
